### ISSUE TITLE
swarm node list

### ISSUE THREAD

**Issue by timchenxiaoyu** [spotify/docker-client#636] opened 2017-02-21 12:43 UTC
how to get all swarm nodes

**Comment by johnflavin** [comment] 2017-02-21 15:03
Currently you can't. The docker REST API added the `GET /nodes` endpoint in version 1.24, and docker-client is not yet completely updated to be compatible with that version of the docker API.

We be happy to review a pull request to add it.

**Comment by davidxia** [comment] 2017-02-21 19:50
Duplicate of https://github.com/spotify/docker-client/issues/543

**Closed by davidxia** 2017-02-21 19:50 UTC
