### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by sayarg** [spotify/docker-client#203] opened 2015-07-03 20:31 UTC
Are there any plans to support docker events? Thanks.

**Comment by davidxia** [comment] 2015-07-14 20:00
@sayarg Closing as this is a duplicate of https://github.com/spotify/docker-client/issues/114. We at spotify don't plan on implementing this anytime soon. But we'd be open to external PRs :)

**Closed by davidxia** 2015-07-14 20:00 UTC
Labels: question
