### ISSUE TITLE
Single value problem of "Healthcheck"

### ISSUE THREAD

**Issue by flexdeviser** [spotify/docker-client#622] opened 2017-02-09 00:43 UTC
## Description

please add Deserialization Feature into "ObjectMapperProvider"

OBJECT_MAPPER.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)

My healthcheck configuration is :
"Healthcheck": {
                "Test": 
                    "CMD-SHELL",
                    "curl --fail http://localhost:80/ || exit 1"
                ],
                "Interval": 5000000000, //  **this is the problem*
                "Timeout": 3000000000
            },

## How to reproduce

Use DockerClient to get a container information

ContainerInfo result = dockerClient.inspectContainer("5938056905b8953eb96b2c2109788d0351e45142631b8066c65009b247bcbf12");

## What happened instead
Can not deserialize instance of java.util.ArrayList out of VALUE_NUMBER_INT token

com.spotify.docker.client.messages.ContainerInfo["Config"]->com.spotify.docker.client.messages.ContainerConfig["Healthcheck"]->java.util.LinkedHashMap["Interval"])

## Software:

- Spotify's docker-client version: [7.0.2]

**Comment by johnflavin** [comment] 2017-02-09 03:40
That object mapper feature would not fix the problem. The issue is that Healthcheck is being deserialized as a `Map<String, List<String>>`, when that does not correctly represent the structure of the object.

I opened #623 to fix this.

**Comment by davidxia** [comment] 2017-02-17 17:51
#623 has been merged.

**Closed by davidxia** 2017-02-17 17:51 UTC

**Comment by flexdeviser** [comment] 2017-02-23 23:54
Could you please change "Interval" and "Timeout" from Integer to Long?

"Interval": 5000000000, // *this is the problem
"Timeout": 3000000000

com.fasterxml.jackson.databind.JsonMappingException: Numeric value (5000000000) out of range of int

**Comment by davidxia** [comment] 2017-02-24 13:35
@flexdeviser Thanks. See PR //github.com/spotify/docker-client/pull/650.
