### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by INotWant** [spotify/docker-client#993] opened 2018-03-18 09:02 UTC
## Description

```bash
#!/usr/bin/env bash
sudo docker cp /home/jie/project/java/qa/src/main/resources/text/qe_text qa:/home/QA/data/qe_text
sudo docker exec qa /usr/bin/python -u /home/QA/application.py > /home/jie/project/java/qa/src/main/resources/result
```
```java
Process process;
ProcessBuilder pb = new ProcessBuilder("/bin/bash", "-c", shellPath);
pb.environment();
process = pb.start();
process.waitFor();
```

1. First, I call `shell` via `java API` and then execute program  in **Docker**. However, It has a bad performance and spends about 2.5s. **My program only needs 1.5s when it's running directly.**

2. Then,I find this project and decide to use it instead of `shell`. Because i think that `shell` via `java API` can execute `fork` so that consumes a lot of time.

3. However, I still need 2.5s when using it. Why? It's bad!!!

## Performance

Has anyone done a performance test? Compare with `shell` via `java API`.

**Comment by mattnworb** [comment] 2018-06-27 12:09
Its not clear to me from this description what the problem is or how you are measuring the time. Are you counting Java startup time? Also the java code example doesn’t make use of docker-client. 

Closing as I’m not sure what the issue here is.

**Closed by mattnworb** 2018-06-27 12:09 UTC
