### ISSUE TITLE
Hijack is incompatible with use of CloseNotifier

### ISSUE THREAD

**Issue by damianopezzotti** [spotify/docker-client#258] opened 2015-11-03 09:25 UTC
Hi,
in some cases, I have a problem invoking execCreate.
The client returns an HTTP error 500 with message "Hijack is incompatible with use of CloseNotifier"

**Comment by mattnworb** [comment] 2015-11-05 17:55
That error message sounds like it would come directly from the docker daemon; the docker source has plenty of references to Hijack and CloseNotifier. 

@damianopezzotti what version of docker are you using? Do you have steps to reproduce?

**Comment by damianopezzotti** [comment] 2015-11-13 08:22
Yes, it seems to be a Docker problem.
The error occurs on a CentOs 7 host with Docker 1.8.2 installed.
If I try to use another Docker host (e.g. Ubuntu hosted on AWS and created using docker-machine) everything works fine

**Comment by rgrunber** [comment] 2015-12-14 18:11
I just ran into this exact issue. Docker is aware of the issue (https://github.com/docker/docker/issues/12845), but since it's a bug in golang (https://github.com/golang/go/issues/9763), most docker clients are working around the problem themselves. I see that a fix for the issue is under review at https://go-review.googlesource.com/#/c/3821/ targetted for golang 1.6.

I guess to work around it, one would need to disable Keep-Alive in the unix/http socket connections, or I guess even having yet another client for only the build() (much like there is a timeout and notimeout client).

**Comment by markgale** [comment] 2016-02-03 09:19
The error message isnt super helpful, but you are right your docker client is keeping a connection, blocking certain further docker api calls. I worked round this by creating my DockerClient in a try-with-resources block e.g:

```
 try (DockerClient dockerClient = new DefaultDockerClient(DEFAULT_DOCKER_SOCK)) {
    dockerClient.doStuff();
}
```

Although this is probably a good pattern anyway, as DockerClient implements closable, so it will tidy up for you.

**Comment by davidxia** [comment] 2017-11-13 18:39
I'm leaning towards closing since this seems like a deeper issue and try with resources provides a workaround. Any objections?

**Comment by mattnworb** [comment] 2017-11-20 21:37
+1

**Closed by mattnworb** 2017-11-20 21:37 UTC
