### ISSUE TITLE
Problem create container

### ISSUE THREAD

**Issue by maroki** [spotify/docker-client#449] opened 2016-06-01 09:59 UTC
I use latest version, when I run the DefaultDockerClient.
My container configuration is:

```
    // Bind container ports to host ports
    String[] dockerPorts = {44444, 59004};
    String[] seleniumPorts = {"4444", "5900"};

    Map<String, List<PortBinding>> portBindings = new HashMap<String, List<PortBinding>>();
    int[] indexes = { 0, 1 };
    for (int index  : indexes){
        List<PortBinding> hostPorts = new ArrayList<PortBinding>();
        hostPorts.add(PortBinding.of("0.0.0.0", dockerPorts[index]));
        portBindings.put(seleniumPorts[index], hostPorts);
    }

     HostConfig hostConfig = HostConfig.builder().portBindings(portBindings).build();

    // Create container with exposed ports
     ContainerConfig containerConfig = ContainerConfig.builder()
            .hostConfig(hostConfig).exposedPorts(seleniumPorts)
            .image("mobillogix/selenium-chrome")
            .build();
```

when i want to create a container :

```
      ContainerCreation creation = docker.createContainer(containerConfig); 
```

I get the following error :
What am I doing wrong? 

```
com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.net.MalformedURLException: unknown protocol: unix
    at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1314)
    at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1266)
    at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:429)
    at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:411)
    at com.mobillogix.activate.logix.job.apex.docker.DockerClientForSelenium.<init>(DockerClientForSelenium.java:55)
    at com.mobillogix.activate.logix.job.apex.selenium.drivers.PhoenixWebDriver.<init>(PhoenixWebDriver.java:46)
    at com.mobillogix.activate.logix.job.apex.selenium.SeleniumLineEnqury.<init>(SeleniumLineEnqury.java:40)
    at com.mobillogix.activate.logix.job.apex.LineEnquiryJob.execute(LineEnquiryJob.java:35)
    at com.mobillogix.activate.logix.service.JobRunner.runJob(JobRunner.java:124)
    at com.mobillogix.activate.logix.service.JobRunner$JobMessageListener.onMessage(JobRunner.java:208)
    at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:746)
    at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:684)
    at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651)
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315)
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:233)
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1150)
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1142)
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1039)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.net.MalformedURLException: unknown protocol: unix
    at org.apache.cxf.endpoint.ClientCallback.get(ClientCallback.java:147)
    at org.apache.cxf.jaxrs.client.JaxrsClientCallback$JaxrsResponseCallback.get(JaxrsClientCallback.java:119)
    at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1264)
    ... 17 more
Caused by: javax.ws.rs.ProcessingException: java.net.MalformedURLException: unknown protocol: unix
    at org.apache.cxf.jaxrs.client.AbstractClient$ConnectionFaultInterceptor.handleMessage(AbstractClient.java:1086)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:112)
    at org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.java:366)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:324)
    at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:636)
    at org.apache.cxf.jaxrs.client.WebClient.doInvokeAsync(WebClient.java:984)
    at org.apache.cxf.jaxrs.client.WebClient$AsyncInvokerImpl.method(WebClient.java:1491)
    ... 18 more
Caused by: java.net.MalformedURLException: unknown protocol: unix
    at java.net.URL.<init>(URL.java:600)
    at java.net.URL.<init>(URL.java:490)
    at java.net.URL.<init>(URL.java:439)
    at java.net.URI.toURL(URI.java:1089)
    at org.apache.cxf.transport.http.Address.getURL(Address.java:60)
    at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:93)
    at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:106)
    at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:497)
    at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:46)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    ... 21 more
```

**Comment by mattnworb** [comment] 2016-06-01 14:09
Sounds like your Jersey client does not support unix sockets, but you are using a DOCKER_HOST value with `unix:///`. You'll have to either use the Apache client (which docker-client adds support on top of for unix sockets) or use a different DOCKER_HOST.

**Comment by davidxia** [comment] 2016-09-24 15:51
@maroki Does this work for you now? If so, can I close this?

**Comment by davidxia** [comment] 2016-12-23 19:17
Closing since this is pretty old. Please try with the latest version, and let us know.

**Closed by davidxia** 2016-12-23 19:17 UTC

**Comment by panga** [comment] 2017-05-15 20:29
I have the same problem using latest version 4.8.0 in a Spring Boot 1.4.x application.

I'm using Apache CXF as JAX-RS client implementation.

`
 Caused by: java.net.MalformedURLException: unknown protocol: unix
at java.net.URL.<init>(URL.java:600) ~[na:1.8.0_121]
at java.net.URL.<init>(URL.java:490) ~[na:1.8.0_121]
at java.net.URL.<init>(URL.java:439) ~[na:1.8.0_121]
at java.net.URI.toURL(URI.java:1089) ~[na:1.8.0_121]
at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[cxf-rt-transports-http-3.1.7.jar!/:3.1.7]
at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:104) ~[cxf-rt-transports-http-3.1.7.jar!/:3.1.7]
at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:117) ~[cxf-rt-transports-http-3.1.7.jar!/:3.1.7]
at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:497) ~[cxf-rt-transports-http-3.1.7.jar!/:3.1.7]
at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:46) ~[cxf-core-3.1.7.jar!/:3.1.7]
... 114 common frames omitted
`

**Comment by miclys** [comment] 2017-05-19 18:08
In my case the problem was with dependency to `cxf-rt-rs-client` which by default is using `org.apache.cxf.jaxrs.client.spec.ClientBuilderImpl` class to initialise client which is not happy with url containing unix protocol.
I could not just remove this dependency so what I have done is I created new file under `resources/META-INF/services/` with name `javax.ws.rs.client.ClientBuilder` and content `org.glassfish.jersey.client.JerseyClientBuilder`
That overrides default client builder which can handle unix protocol.

**Comment by bryantrobbins** [comment] 2017-05-22 19:34
Apologies for bumping an old thread, but I also ran into a similar issue when trying to mix Spring Boot, Apache CXF, and docker-client. I will see if I can post back a new issue with a reproducible setup.

**Comment by pmartin8** [comment] 2018-03-21 19:06
I also get the error when Apache CXF is included in the classpath.
