### ISSUE TITLE
DockerTimeoutException at image pulling but manual pull is working fine

### ISSUE THREAD

**Issue by zhengl7** [spotify/docker-client#512] opened 2016-10-04 00:48 UTC
## Description

When calling `com.spotify.docker.client.DockerClient#pull(java.lang.String)` to pull an image from a private registry, sometimes will see this error thrown at the end of pulling process, while the progress shows everything is downloaded and extracted,

```
2016-09-30 14:56:34.315 - INFO LoggingPullHandler: pull myregistry.com:myimage:1.0: ProgressMessage{id=046135e4fd93, status=Extracting, stream=null, error=null, progress=347.4 MB/347.4 MB, progressDetail=ProgressDetail{current=347362857, start=0, total=347362857}}

...

Caused by: com.spotify.docker.client.exceptions.DockerTimeoutException: Timeout: POST http://mymachine.com:4243/images/create?fromImage=myregistry.com:myimage&tag=1.0
        at com.spotify.docker.client.ProgressStream.hasNextMessage(ProgressStream.java:58)
        at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:76)
        at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:987)
        at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:961)
        at com.spotify.docker.client.DefaultDockerClient.pull(DefaultDockerClient.java:955)
        ... 12 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
        at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
        at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:227)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:186)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:101)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:302)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2904)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2899)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
        at com.fasterxml.jackson.databind.MappingIterator.hasNextValue(MappingIterator.java:240)
        at com.spotify.docker.client.ProgressStream.hasNextMessage(ProgressStream.java:56)
        ... 17 more
```

However, when trying to use `docker pull` or call Docker REST API directly the pulling will always succeed.
## How to reproduce

Actually not sure about this. The issue happens randomly for me, but more frequently on a system where the pulling is slower. 
## What do you expect

This is probably more of a question of why this would happen sometimes using the spotify docker-client. 

I know there are two attributes 

`com.spotify.docker.client.DefaultDockerClient.Builder#connectTimeoutMillis`
`com.spotify.docker.client.DefaultDockerClient.Builder#readTimeoutMillis`

but not sure if increasing these two would help in this case. 
## Software:
- `docker version`: 

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
```
- Spotify's docker-client version: [4.0.6]
## Full backtrace

As pasted above.

**Comment by rgrunber** [comment] 2016-11-29 16:11
I think this could be resolved easily by having 'pull' use a 'noTimeoutClient' like some of the other commands (spotify/docker-client@b76fc63). Basically, operations that can take an arbitrary amount of time need to be using a connection that allows unlimited timeout (where timeout is defined by the maximum amount of time allowed to elapse between non-empty reads by the client).

On the other hand, one could argue that if a pull had inactivity for more than 30s, then there's clearly some network connectivity issues and clients should actually handle the exception and inform the user. Is this consistently reproducible in spotify/docker-client and not reproducible in the docker cli ?

I've run into a similar reports (See https://bugs.eclipse.org/bugs/show_bug.cgi?id=494131) but it always seemed like network issues.

**Comment by Jeckyli** [comment] 2016-12-13 02:07
I ended up resolving it by calling `com.spotify.docker.client.DefaultDockerClient.Builder#connectTimeoutMillis(long)` to explicitly give it a longer timeout to 30 seconds. 

But I'm still suspecting it's not a pure intermittent network issue. Using cli always succeeds while user spotify client would fail very frequently without this tweaking. It might be due to the cli by default has a more tolerant timeout setting, but I haven't got time to find it out yet.

**Comment by davidxia** [comment] 2017-11-13 18:50
I've run into this before as well. I tend to agree with @rgrunber that if the pull times out after the default 30 seconds, it's probably better to fail. To be clear the 30 seconds TTL in DefaultDockerClient is specifically the max period of inactivity between two consecutive data packets.

I'll close this issue as there's a workaround but am open to discussing more if this is an issue for more people.

**Closed by davidxia** 2017-11-13 18:50 UTC
